version: "3.1"

services:
  backend-service:
    container_name: ${CONTAINER_NAME}
    image: ${DOCKER_REPOSITORY}:latest
    hostname: prod.moneystats.angular
    ports:
      - "10000:80"
    networks:
      docker-network:
        aliases:
          - prod.moneystats.angular

networks:
  docker-network:
    external: true
