# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy-STG

on:
  push:
    branches: [develop]

jobs:
  checkout:
    name: 🔧 Checkout
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false

  setting-up:
    name: 🔧 Setting Up
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: 🔧 Use Node.js 16.13.2
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"

  dependency:
    name: 📦 Installing Dependency
    runs-on: ubuntu-latest
    needs: [checkout, setting-up]
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: "📦 Dependency Injection"
        run: |
          npm install -g @angular/cli
          npm install --force
  build:
    name: 📂 Build
    runs-on: ubuntu-latest
    needs: [setting-up, dependency]
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Grant execute permission to script
        run: chmod +x ./rename.sh

      - name: 📂 Build
        run: |
          npm install -g @angular/cli
          npm install --force
          npm run staging
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    environment:
      name: stg-moneystats-angular
    needs:
      - dependency
      - build
    steps:
      - name: Grant execute permission to script
        run: chmod +x ./rename.sh

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg config=staging --tag angular-moneystats:$(date +%s)

      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
          tags: ${{ steps.package-version.outputs.current-version}}, latest
          buildArgs: config=staging
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          multiPlatform: true
          platform: linux/amd64,linux/arm64
