# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Prod Deploy MoneyStats

on:
  push:
    branches: [master]

jobs:
  checkout:
    name: 🔧 Checkout
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

  setting-up:
    name: 🔧 Setting Up
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: 🔧 Use Node.js 16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"

  dependency:
    name: 📦 Installing Dependency
    runs-on: ubuntu-latest
    needs: [checkout, setting-up]
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: "📦 Dependency Injection"
        run: |
          npm install -g @angular/cli
          npm install --force
  build:
    name: 📂 Build
    runs-on: ubuntu-latest
    needs: [setting-up, dependency]
    steps:
      - name: "☁️ Checkout Repository"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: 📂 Build
        run: |
          npm install -g @angular/cli
          npm install --force
          npm run prod
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    environment:
      name: prod-moneystats-angular
    needs:
      - dependency
      - build
    steps:
      #- uses: actions/checkout@v2
      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --build-arg config=prod --tag angular-moneystats:$(date +%s)

      #- name: Install Dependency
      #  run: npm install --force

      #- name: Build
      #  run: npm run build --configuration=development

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: config=production
